/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/do-re-mi': RouteRecordInfo<
      '/do-re-mi',
      '/do-re-mi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/do-re-mi-test': RouteRecordInfo<
      '/do-re-mi-test',
      '/do-re-mi-test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pitch-detector': RouteRecordInfo<
      '/pitch-detector',
      '/pitch-detector',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pitch-detector-test': RouteRecordInfo<
      '/pitch-detector-test',
      '/pitch-detector-test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tone-detector': RouteRecordInfo<
      '/tone-detector',
      '/tone-detector',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tone-detector-test': RouteRecordInfo<
      '/tone-detector-test',
      '/tone-detector-test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/do-re-mi.vue': {
      routes:
        | '/do-re-mi'
      views:
        | never
    }
    'src/pages/do-re-mi-test.vue': {
      routes:
        | '/do-re-mi-test'
      views:
        | never
    }
    'src/pages/pitch-detector.vue': {
      routes:
        | '/pitch-detector'
      views:
        | never
    }
    'src/pages/pitch-detector-test.vue': {
      routes:
        | '/pitch-detector-test'
      views:
        | never
    }
    'src/pages/tone-detector.vue': {
      routes:
        | '/tone-detector'
      views:
        | never
    }
    'src/pages/tone-detector-test.vue': {
      routes:
        | '/tone-detector-test'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
