/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...pathMatch]': RouteRecordInfo<
      '/[...pathMatch]',
      '/:pathMatch(.*)',
      { pathMatch: ParamValue<true> },
      { pathMatch: ParamValue<false> },
      | never
    >,
    '/do-re-mi': RouteRecordInfo<
      '/do-re-mi',
      '/do-re-mi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/do-re-mi-test': RouteRecordInfo<
      '/do-re-mi-test',
      '/do-re-mi-test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/games': RouteRecordInfo<
      '/games',
      '/games',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/grace-kelly-challenge': RouteRecordInfo<
      '/grace-kelly-challenge',
      '/grace-kelly-challenge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guitar': RouteRecordInfo<
      '/guitar',
      '/guitar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notes': RouteRecordInfo<
      '/notes',
      '/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notes-overview-test': RouteRecordInfo<
      '/notes-overview-test',
      '/notes-overview-test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/piano': RouteRecordInfo<
      '/piano',
      '/piano',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pitch-detector': RouteRecordInfo<
      '/pitch-detector',
      '/pitch-detector',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pitch-detector-test': RouteRecordInfo<
      '/pitch-detector-test',
      '/pitch-detector-test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pitch-game': RouteRecordInfo<
      '/pitch-game',
      '/pitch-game',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pitch-game-test': RouteRecordInfo<
      '/pitch-game-test',
      '/pitch-game-test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sing-tone': RouteRecordInfo<
      '/sing-tone',
      '/sing-tone',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sing-tone-test': RouteRecordInfo<
      '/sing-tone-test',
      '/sing-tone-test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/singfly': RouteRecordInfo<
      '/singfly',
      '/singfly',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/singfly-test': RouteRecordInfo<
      '/singfly-test',
      '/singfly-test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tone-detector': RouteRecordInfo<
      '/tone-detector',
      '/tone-detector',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tone-detector-test': RouteRecordInfo<
      '/tone-detector-test',
      '/tone-detector-test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools': RouteRecordInfo<
      '/tools',
      '/tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tuner': RouteRecordInfo<
      '/tuner',
      '/tuner',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tuner-test': RouteRecordInfo<
      '/tuner-test',
      '/tuner-test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ukulele': RouteRecordInfo<
      '/ukulele',
      '/ukulele',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/warm-up': RouteRecordInfo<
      '/warm-up',
      '/warm-up',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/warm-up-test': RouteRecordInfo<
      '/warm-up-test',
      '/warm-up-test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...pathMatch].vue': {
      routes:
        | '/[...pathMatch]'
      views:
        | never
      pathParamNames:
        | 'pathMatch'
    }
    'src/pages/do-re-mi.vue': {
      routes:
        | '/do-re-mi'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/do-re-mi-test.vue': {
      routes:
        | '/do-re-mi-test'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/games.vue': {
      routes:
        | '/games'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/grace-kelly-challenge.vue': {
      routes:
        | '/grace-kelly-challenge'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/guitar.vue': {
      routes:
        | '/guitar'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/notes.vue': {
      routes:
        | '/notes'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/notes-overview-test.vue': {
      routes:
        | '/notes-overview-test'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/piano.vue': {
      routes:
        | '/piano'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/pitch-detector.vue': {
      routes:
        | '/pitch-detector'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/pitch-detector-test.vue': {
      routes:
        | '/pitch-detector-test'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/pitch-game.vue': {
      routes:
        | '/pitch-game'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/pitch-game-test.vue': {
      routes:
        | '/pitch-game-test'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/sing-tone.vue': {
      routes:
        | '/sing-tone'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/sing-tone-test.vue': {
      routes:
        | '/sing-tone-test'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/singfly.vue': {
      routes:
        | '/singfly'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/singfly-test.vue': {
      routes:
        | '/singfly-test'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tone-detector.vue': {
      routes:
        | '/tone-detector'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tone-detector-test.vue': {
      routes:
        | '/tone-detector-test'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools.vue': {
      routes:
        | '/tools'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tuner.vue': {
      routes:
        | '/tuner'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tuner-test.vue': {
      routes:
        | '/tuner-test'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ukulele.vue': {
      routes:
        | '/ukulele'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/warm-up.vue': {
      routes:
        | '/warm-up'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/warm-up-test.vue': {
      routes:
        | '/warm-up-test'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
