/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ACCIDENTAL_STYLE_OPTIONS: typeof import('./composables/accidentalStyle').ACCIDENTAL_STYLE_OPTIONS
  const CLARITY_STEP: typeof import('./composables/useSettings').CLARITY_STEP
  const DEFAULT_CLARITY_THRESHOLD: typeof import('./composables/useSettings').DEFAULT_CLARITY_THRESHOLD
  const DEFAULT_HOLD_DURATION_MS: typeof import('./composables/useDoReMiGame').DEFAULT_HOLD_DURATION_MS
  const DEFAULT_PREVIEW_ENABLED: typeof import('./composables/useSettings').DEFAULT_PREVIEW_ENABLED
  const DEFAULT_SCALE_MODE: typeof import('./composables/useDoReMiGame').DEFAULT_SCALE_MODE
  const DEFAULT_STARTING_SEMITONE_OFFSET: typeof import('./composables/useDoReMiGame').DEFAULT_STARTING_SEMITONE_OFFSET
  const EffectScope: typeof import('vue').EffectScope
  const GRACE_PERIOD_MS: typeof import('./composables/useDoReMiGame').GRACE_PERIOD_MS
  const HOLD_DURATION_MS: typeof import('./composables/useDoReMiGame').HOLD_DURATION_MS
  const MAX_CENTS_DEVIATION: typeof import('./composables/useDoReMiGame').MAX_CENTS_DEVIATION
  const MAX_CLARITY_THRESHOLD: typeof import('./composables/useSettings').MAX_CLARITY_THRESHOLD
  const MIN_CLARITY_THRESHOLD: typeof import('./composables/useSettings').MIN_CLARITY_THRESHOLD
  const NOTE_INTERVAL_MS: typeof import('./composables/useDoReMiPlaySequence').NOTE_INTERVAL_MS
  const SCALE_MODE_OPTIONS: typeof import('./composables/useDoReMiGame').SCALE_MODE_OPTIONS
  const SCALE_STEPS: typeof import('./composables/useDoReMiGame').SCALE_STEPS
  const START_TONE_OPTIONS: typeof import('./composables/useDoReMiGame').START_TONE_OPTIONS
  const TOO_LOW_OR_HIGH_HINT_MS: typeof import('./composables/useDoReMiGame').TOO_LOW_OR_HIGH_HINT_MS
  const computed: typeof import('vue').computed
  const confettiKey: typeof import('./composables/useConfetti').confettiKey
  const createApp: typeof import('vue').createApp
  const createMockToneEngine: typeof import('./composables/toneEngine.mock').createMockToneEngine
  const createTonejsAdapter: typeof import('./composables/toneEngine').createTonejsAdapter
  const customRef: typeof import('vue').customRef
  const debugLog: typeof import('@/utils/logger').debugLog
  const defaultToneEngine: typeof import('./composables/toneEngine').defaultToneEngine
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isAccidentalStyle: typeof import('./composables/accidentalStyle').isAccidentalStyle
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const isToneLabelMode: typeof import('./composables/toneLabelMode').isToneLabelMode
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const prewarmGuitarFretboard: typeof import('./composables/useGuitarSampler').prewarmGuitarFretboard
  const prewarmStandardTuning: typeof import('./composables/useGuitarSampler').prewarmStandardTuning
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const setupConfettiOnWindow: typeof import('./composables/useConfetti').setupConfettiOnWindow
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const toneLabelModeToFlags: typeof import('./composables/toneLabelMode').toneLabelModeToFlags
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAccidentalStyle: typeof import('./composables/accidentalStyle').useAccidentalStyle
  const useAttrs: typeof import('vue').useAttrs
  const useConfetti: typeof import('./composables/useConfetti').useConfetti
  const useConfettiStore: typeof import('./stores/useConfettiStore').useConfettiStore
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDarkMode: typeof import('./composables/useDarkMode').useDarkMode
  const useDoReMiGame: typeof import('./composables/useDoReMiGame').useDoReMiGame
  const useDoReMiPlaySequence: typeof import('./composables/useDoReMiPlaySequence').useDoReMiPlaySequence
  const useDocumentDirection: typeof import('./composables/useDocumentDirection').useDocumentDirection
  const useDocumentMeta: typeof import('./composables/useDocumentMeta').useDocumentMeta
  const useDuetPitchDetection: typeof import('./composables/useDuetPitchDetection').useDuetPitchDetection
  const useErrorToastStore: typeof import('./stores/useErrorToastStore').useErrorToastStore
  const useFaviconPermissionColor: typeof import('./composables/useFaviconPermissionColor').useFaviconPermissionColor
  const useFireConfetti: typeof import('./composables/useConfetti').useFireConfetti
  const useGuitarSampler: typeof import('./composables/useGuitarSampler').useGuitarSampler
  const useI18n: typeof import('vue-i18n').useI18n
  const useId: typeof import('vue').useId
  const useIdlePreview: typeof import('./composables/useIdlePreview').useIdlePreview
  const useIsInstalledPwa: typeof import('./composables/useIsInstalledPwa').useIsInstalledPwa
  const useIsRtl: typeof import('./composables/useDocumentDirection').useIsRtl
  const useLink: typeof import('vue-router').useLink
  const useMicrophonePermission: typeof import('./composables/useMicrophonePermission').useMicrophonePermission
  const useModel: typeof import('vue').useModel
  const useMultiToneDetection: typeof import('./composables/useMultiToneDetection').useMultiToneDetection
  const usePitchDetection: typeof import('./composables/usePitchDetection').usePitchDetection
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useScaleModeGroups: typeof import('./composables/useScaleModeGroups').useScaleModeGroups
  const useScaleModeLabel: typeof import('./composables/useScaleModeGroups').useScaleModeLabel
  const useScaleModeOptions: typeof import('./composables/useScaleModeOptions').useScaleModeOptions
  const useScrollEdgeMask: typeof import('./composables/useScrollEdgeMask').useScrollEdgeMask
  const useSettings: typeof import('./composables/useSettings').useSettings
  const useSimulatedMultiToneDetection: typeof import('./composables/useSimulatedMultiToneDetection').useSimulatedMultiToneDetection
  const useSimulatedPitchDetection: typeof import('./composables/useSimulatedPitchDetection').useSimulatedPitchDetection
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useToneLabelMode: typeof import('./composables/toneLabelMode').useToneLabelMode
  const useToneLabelModeOptions: typeof import('./composables/toneLabelMode').useToneLabelModeOptions
  const useToneModeStore: typeof import('./stores/useToneModeStore').useToneModeStore
  const useTonePlayer: typeof import('./composables/useTonePlayer').useTonePlayer
  const useVoiceRangeIndex: typeof import('./composables/useVoiceRangeIndex').useVoiceRangeIndex
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { AccidentalStyle } from './composables/accidentalStyle'
  import('./composables/accidentalStyle')
  // @ts-ignore
  export type { ToneMode, ToneEngine } from './composables/toneEngine'
  import('./composables/toneEngine')
  // @ts-ignore
  export type { ToneLabelMode } from './composables/toneLabelMode'
  import('./composables/toneLabelMode')
  // @ts-ignore
  export type { DuetLane, DuetLaneDetection } from './composables/useDuetPitchDetection'
  import('./composables/useDuetPitchDetection')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly ACCIDENTAL_STYLE_OPTIONS: UnwrapRef<typeof import('./composables/accidentalStyle')['ACCIDENTAL_STYLE_OPTIONS']>
    readonly CLARITY_STEP: UnwrapRef<typeof import('./composables/useSettings')['CLARITY_STEP']>
    readonly DEFAULT_CLARITY_THRESHOLD: UnwrapRef<typeof import('./composables/useSettings')['DEFAULT_CLARITY_THRESHOLD']>
    readonly DEFAULT_PREVIEW_ENABLED: UnwrapRef<typeof import('./composables/useSettings')['DEFAULT_PREVIEW_ENABLED']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly MAX_CLARITY_THRESHOLD: UnwrapRef<typeof import('./composables/useSettings')['MAX_CLARITY_THRESHOLD']>
    readonly MIN_CLARITY_THRESHOLD: UnwrapRef<typeof import('./composables/useSettings')['MIN_CLARITY_THRESHOLD']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createMockToneEngine: UnwrapRef<typeof import('./composables/toneEngine.mock')['createMockToneEngine']>
    readonly createTonejsAdapter: UnwrapRef<typeof import('./composables/toneEngine')['createTonejsAdapter']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly debugLog: UnwrapRef<typeof import('@/utils/logger')['debugLog']>
    readonly defaultToneEngine: UnwrapRef<typeof import('./composables/toneEngine')['defaultToneEngine']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isAccidentalStyle: UnwrapRef<typeof import('./composables/accidentalStyle')['isAccidentalStyle']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly isToneLabelMode: UnwrapRef<typeof import('./composables/toneLabelMode')['isToneLabelMode']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly prewarmGuitarFretboard: UnwrapRef<typeof import('./composables/useGuitarSampler')['prewarmGuitarFretboard']>
    readonly prewarmStandardTuning: UnwrapRef<typeof import('./composables/useGuitarSampler')['prewarmStandardTuning']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly toneLabelModeToFlags: UnwrapRef<typeof import('./composables/toneLabelMode')['toneLabelModeToFlags']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAccidentalStyle: UnwrapRef<typeof import('./composables/accidentalStyle')['useAccidentalStyle']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useConfetti: UnwrapRef<typeof import('./composables/useConfetti')['useConfetti']>
    readonly useConfettiStore: UnwrapRef<typeof import('./stores/useConfettiStore')['useConfettiStore']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDarkMode: UnwrapRef<typeof import('./composables/useDarkMode')['useDarkMode']>
    readonly useDocumentDirection: UnwrapRef<typeof import('./composables/useDocumentDirection')['useDocumentDirection']>
    readonly useDocumentMeta: UnwrapRef<typeof import('./composables/useDocumentMeta')['useDocumentMeta']>
    readonly useDuetPitchDetection: UnwrapRef<typeof import('./composables/useDuetPitchDetection')['useDuetPitchDetection']>
    readonly useErrorToastStore: UnwrapRef<typeof import('./stores/useErrorToastStore')['useErrorToastStore']>
    readonly useFaviconPermissionColor: UnwrapRef<typeof import('./composables/useFaviconPermissionColor')['useFaviconPermissionColor']>
    readonly useGuitarSampler: UnwrapRef<typeof import('./composables/useGuitarSampler')['useGuitarSampler']>
    readonly useI18n: UnwrapRef<typeof import('vue-i18n')['useI18n']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useIdlePreview: UnwrapRef<typeof import('./composables/useIdlePreview')['useIdlePreview']>
    readonly useIsInstalledPwa: UnwrapRef<typeof import('./composables/useIsInstalledPwa')['useIsInstalledPwa']>
    readonly useIsRtl: UnwrapRef<typeof import('./composables/useDocumentDirection')['useIsRtl']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useMicrophonePermission: UnwrapRef<typeof import('./composables/useMicrophonePermission')['useMicrophonePermission']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly usePitchDetection: UnwrapRef<typeof import('./composables/usePitchDetection')['usePitchDetection']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useScaleModeGroups: UnwrapRef<typeof import('./composables/useScaleModeGroups')['useScaleModeGroups']>
    readonly useScaleModeLabel: UnwrapRef<typeof import('./composables/useScaleModeGroups')['useScaleModeLabel']>
    readonly useScrollEdgeMask: UnwrapRef<typeof import('./composables/useScrollEdgeMask')['useScrollEdgeMask']>
    readonly useSettings: UnwrapRef<typeof import('./composables/useSettings')['useSettings']>
    readonly useSimulatedPitchDetection: UnwrapRef<typeof import('./composables/useSimulatedPitchDetection')['useSimulatedPitchDetection']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useToneLabelMode: UnwrapRef<typeof import('./composables/toneLabelMode')['useToneLabelMode']>
    readonly useToneLabelModeOptions: UnwrapRef<typeof import('./composables/toneLabelMode')['useToneLabelModeOptions']>
    readonly useToneModeStore: UnwrapRef<typeof import('./stores/useToneModeStore')['useToneModeStore']>
    readonly useTonePlayer: UnwrapRef<typeof import('./composables/useTonePlayer')['useTonePlayer']>
    readonly useVoiceRangeIndex: UnwrapRef<typeof import('./composables/useVoiceRangeIndex')['useVoiceRangeIndex']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}