/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const DEFAULT_HOLD_DURATION_MS: typeof import('./composables/useDoReMiGame').DEFAULT_HOLD_DURATION_MS
  const DEFAULT_SCALE_MODE: typeof import('./composables/useDoReMiGame').DEFAULT_SCALE_MODE
  const DEFAULT_STARTING_SEMITONE_OFFSET: typeof import('./composables/useDoReMiGame').DEFAULT_STARTING_SEMITONE_OFFSET
  const EffectScope: typeof import('vue').EffectScope
  const GRACE_PERIOD_MS: typeof import('./composables/useDoReMiGame').GRACE_PERIOD_MS
  const HOLD_DURATION_MS: typeof import('./composables/useDoReMiGame').HOLD_DURATION_MS
  const MAX_CENTS_DEVIATION: typeof import('./composables/useDoReMiGame').MAX_CENTS_DEVIATION
  const NOTE_INTERVAL_MS: typeof import('./composables/useDoReMiPlaySequence').NOTE_INTERVAL_MS
  const SCALE_MODE_OPTIONS: typeof import('./composables/useDoReMiGame').SCALE_MODE_OPTIONS
  const SCALE_STEPS: typeof import('./composables/useDoReMiGame').SCALE_STEPS
  const START_TONE_OPTIONS: typeof import('./composables/useDoReMiGame').START_TONE_OPTIONS
  const TOO_LOW_OR_HIGH_HINT_MS: typeof import('./composables/useDoReMiGame').TOO_LOW_OR_HIGH_HINT_MS
  const computed: typeof import('vue').computed
  const confettiKey: typeof import('./composables/useConfetti').confettiKey
  const createApp: typeof import('vue').createApp
  const createMockToneEngine: typeof import('./composables/toneEngine.mock').createMockToneEngine
  const createTonejsAdapter: typeof import('./composables/toneEngine').createTonejsAdapter
  const customRef: typeof import('vue').customRef
  const debugLog: typeof import('@/utils/logger').debugLog
  const defaultToneEngine: typeof import('./composables/toneEngine').defaultToneEngine
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const effectScope: typeof import('vue').effectScope
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const setupConfettiOnWindow: typeof import('./composables/useConfetti').setupConfettiOnWindow
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useConfetti: typeof import('./composables/useConfetti').useConfetti
  const useConfettiStore: typeof import('./stores/useConfettiStore').useConfettiStore
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDoReMiGame: typeof import('./composables/useDoReMiGame').useDoReMiGame
  const useDoReMiPlaySequence: typeof import('./composables/useDoReMiPlaySequence').useDoReMiPlaySequence
  const useDocumentDirection: typeof import('./composables/useDocumentDirection').useDocumentDirection
  const useErrorToastStore: typeof import('./stores/useErrorToastStore').useErrorToastStore
  const useFireConfetti: typeof import('./composables/useConfetti').useFireConfetti
  const useI18n: typeof import('vue-i18n').useI18n
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useMicrophonePermission: typeof import('./composables/useMicrophonePermission').useMicrophonePermission
  const useModel: typeof import('vue').useModel
  const useMultiToneDetection: typeof import('./composables/useMultiToneDetection').useMultiToneDetection
  const usePitchDetection: typeof import('./composables/usePitchDetection').usePitchDetection
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSimulatedMultiToneDetection: typeof import('./composables/useSimulatedMultiToneDetection').useSimulatedMultiToneDetection
  const useSimulatedPitchDetection: typeof import('./composables/useSimulatedPitchDetection').useSimulatedPitchDetection
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTonePlayer: typeof import('./composables/useTonePlayer').useTonePlayer
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { DetectedTone, ToneDetectionResult } from './composables/toneDetectionTypes'
  import('./composables/toneDetectionTypes')
  // @ts-ignore
  export type { ToneMode, ToneEngine } from './composables/toneEngine'
  import('./composables/toneEngine')
  // @ts-ignore
  export type { DoReMiGameResult, DoReMiGameOptions, PitchDetectionProvider, ScaleStep } from './composables/useDoReMiGame'
  import('./composables/useDoReMiGame')
  // @ts-ignore
  export type { SimulatedToneConfig } from './composables/useSimulatedMultiToneDetection'
  import('./composables/useSimulatedMultiToneDetection')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly DEFAULT_HOLD_DURATION_MS: UnwrapRef<typeof import('./composables/useDoReMiGame')['DEFAULT_HOLD_DURATION_MS']>
    readonly DEFAULT_SCALE_MODE: UnwrapRef<typeof import('./composables/useDoReMiGame')['DEFAULT_SCALE_MODE']>
    readonly DEFAULT_STARTING_SEMITONE_OFFSET: UnwrapRef<typeof import('./composables/useDoReMiGame')['DEFAULT_STARTING_SEMITONE_OFFSET']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly GRACE_PERIOD_MS: UnwrapRef<typeof import('./composables/useDoReMiGame')['GRACE_PERIOD_MS']>
    readonly MAX_CENTS_DEVIATION: UnwrapRef<typeof import('./composables/useDoReMiGame')['MAX_CENTS_DEVIATION']>
    readonly NOTE_INTERVAL_MS: UnwrapRef<typeof import('./composables/useDoReMiPlaySequence')['NOTE_INTERVAL_MS']>
    readonly SCALE_MODE_OPTIONS: UnwrapRef<typeof import('./composables/useDoReMiGame')['SCALE_MODE_OPTIONS']>
    readonly START_TONE_OPTIONS: UnwrapRef<typeof import('./composables/useDoReMiGame')['START_TONE_OPTIONS']>
    readonly TOO_LOW_OR_HIGH_HINT_MS: UnwrapRef<typeof import('./composables/useDoReMiGame')['TOO_LOW_OR_HIGH_HINT_MS']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createMockToneEngine: UnwrapRef<typeof import('./composables/toneEngine.mock')['createMockToneEngine']>
    readonly createTonejsAdapter: UnwrapRef<typeof import('./composables/toneEngine')['createTonejsAdapter']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly debugLog: UnwrapRef<typeof import('@/utils/logger')['debugLog']>
    readonly defaultToneEngine: UnwrapRef<typeof import('./composables/toneEngine')['defaultToneEngine']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useConfetti: UnwrapRef<typeof import('./composables/useConfetti')['useConfetti']>
    readonly useConfettiStore: UnwrapRef<typeof import('./stores/useConfettiStore')['useConfettiStore']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDoReMiGame: UnwrapRef<typeof import('./composables/useDoReMiGame')['useDoReMiGame']>
    readonly useDoReMiPlaySequence: UnwrapRef<typeof import('./composables/useDoReMiPlaySequence')['useDoReMiPlaySequence']>
    readonly useDocumentDirection: UnwrapRef<typeof import('./composables/useDocumentDirection')['useDocumentDirection']>
    readonly useErrorToastStore: UnwrapRef<typeof import('./stores/useErrorToastStore')['useErrorToastStore']>
    readonly useI18n: UnwrapRef<typeof import('vue-i18n')['useI18n']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useMicrophonePermission: UnwrapRef<typeof import('./composables/useMicrophonePermission')['useMicrophonePermission']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useMultiToneDetection: UnwrapRef<typeof import('./composables/useMultiToneDetection')['useMultiToneDetection']>
    readonly usePitchDetection: UnwrapRef<typeof import('./composables/usePitchDetection')['usePitchDetection']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSimulatedMultiToneDetection: UnwrapRef<typeof import('./composables/useSimulatedMultiToneDetection')['useSimulatedMultiToneDetection']>
    readonly useSimulatedPitchDetection: UnwrapRef<typeof import('./composables/useSimulatedPitchDetection')['useSimulatedPitchDetection']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useTonePlayer: UnwrapRef<typeof import('./composables/useTonePlayer')['useTonePlayer']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}