/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrowUp: typeof import('./components/icons/ArrowUp.vue')['default']
    Badge: typeof import('./components/generic/Badge.vue')['default']
    Button: typeof import('./components/generic/Button.vue')['default']
    CentsDeviationBar: typeof import('./components/generic/CentsDeviationBar.vue')['default']
    DetectedToneCard: typeof import('./components/tone-detector/DetectedToneCard.vue')['default']
    DoReMiDisplay: typeof import('./components/do-re-mi/DoReMiDisplay.vue')['default']
    DoReMiNoteTarget: typeof import('./components/do-re-mi/DoReMiNoteTarget.vue')['default']
    DoReMiPage: typeof import('./components/do-re-mi/DoReMiPage.vue')['default']
    DoReMiScale: typeof import('./components/do-re-mi/DoReMiScale.vue')['default']
    DoReMiScaleItem: typeof import('./components/do-re-mi/DoReMiScaleItem.vue')['default']
    DoReMiTestPage: typeof import('./components/do-re-mi/DoReMiTestPage.vue')['default']
    ErrorToast: typeof import('./components/generic/ErrorToast.vue')['default']
    GitHubIcon: typeof import('./components/icons/GitHubIcon.vue')['default']
    LandingPage: typeof import('./components/LandingPage.vue')['default']
    LanguageSwitcher: typeof import('./components/generic/LanguageSwitcher.vue')['default']
    MusicNote: typeof import('./components/icons/MusicNote.vue')['default']
    PitchDetectorDisplay: typeof import('./components/pitch-detector/PitchDetectorDisplay.vue')['default']
    PitchDetectorPage: typeof import('./components/pitch-detector/PitchDetectorPage.vue')['default']
    PitchDetectorTestPage: typeof import('./components/pitch-detector/PitchDetectorTestPage.vue')['default']
    PitchDisplay: typeof import('./components/pitch-detector/PitchDisplay.vue')['default']
    PitchHistoryChart: typeof import('./components/pitch-detector/PitchHistoryChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/generic/Select.vue')['default']
    SettingsSlider: typeof import('./components/tone-detector/SettingsSlider.vue')['default']
    ToneDetectorDisplay: typeof import('./components/tone-detector/ToneDetectorDisplay.vue')['default']
    ToneDetectorPage: typeof import('./components/tone-detector/ToneDetectorPage.vue')['default']
    ToneDetectorTestPage: typeof import('./components/tone-detector/ToneDetectorTestPage.vue')['default']
    ToneModeSelect: typeof import('./components/generic/ToneModeSelect.vue')['default']
    TopBar: typeof import('./components/generic/TopBar.vue')['default']
  }
}
