/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrowUp: typeof import('./components/icons/ArrowUp.vue')['default']
    BasicButton: typeof import('./components/generic/BasicButton.vue')['default']
    BasicSelect: typeof import('./components/generic/BasicSelect.vue')['default']
    CentsDeviationBar: typeof import('./components/generic/CentsDeviationBar.vue')['default']
    DoReMiNoteTarget: typeof import('./components/do-re-mi/DoReMiNoteTarget.vue')['default']
    DoReMiPage: typeof import('./components/do-re-mi/DoReMiPage.vue')['default']
    DoReMiScale: typeof import('./components/do-re-mi/DoReMiScale.vue')['default']
    DoReMiScaleItem: typeof import('./components/do-re-mi/DoReMiScaleItem.vue')['default']
    GitHubIcon: typeof import('./components/icons/GitHubIcon.vue')['default']
    LandingPage: typeof import('./components/LandingPage.vue')['default']
    LanguageSwitcher: typeof import('./components/generic/LanguageSwitcher.vue')['default']
    MusicNote: typeof import('./components/icons/MusicNote.vue')['default']
    PitchDetectorPage: typeof import('./components/pitch-detector/PitchDetectorPage.vue')['default']
    PitchDetectorTestPage: typeof import('./components/pitch-detector/PitchDetectorTestPage.vue')['default']
    PitchDisplay: typeof import('./components/pitch-detector/PitchDisplay.vue')['default']
    PitchHistoryChart: typeof import('./components/pitch-detector/PitchHistoryChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToneDetectorPage: typeof import('./components/tone-detector/ToneDetectorPage.vue')['default']
    ToneModeSelect: typeof import('./components/generic/ToneModeSelect.vue')['default']
    TopBar: typeof import('./components/generic/TopBar.vue')['default']
  }
}
